apiVersion: v1
kind: Service
metadata:
  name: edge-plus
  namespace: plus
spec:
  ports:
  - name: ingress
    port: 10809
    protocol: TCP
    targetPort: 10809
  selector:
    greymatter.io/cluster: edge-plus
  type: LoadBalancer
